export const FETCH = 'FETCH';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_FULFILLED = 'FETCH_FULFILLED';
export const FETCH_REJECTED = 'FETCH_REJECTED';

export const CHANGE_ITEM = 'CHANGE_ITEM';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_FULFILLED = 'ADD_ITEM_FULFILLED';
export const ADD_ITEM_REJECTED = 'ADD_ITEM_REJECTED';

export const SAVE_ITEM = 'SAVE_ITEM';
export const SAVE_ITEM_PENDING = 'SAVE_ITEM_PENDING';
export const SAVE_ITEM_FULFILLED = 'SAVE_ITEM_FULFILLED';
export const SAVE_ITEM_REJECTED = 'SAVE_ITEM_REJECTED';
