export const FETCH = 'FETCH';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_FULFILLED = 'FETCH_FULFILLED';
export const FETCH_REJECTED = 'FETCH_REJECTED';

export const CHANGE_ADD_ITEM = 'CHANGE_ADD_ITEM';
export const CHANGE_LIST_ITEM = 'CHANGE_LIST_ITEM';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_FILTER_FULFILLED = 'CHANGE_FILTER_FULFILLED';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_FULFILLED = 'ADD_ITEM_FULFILLED';
export const ADD_ITEM_REJECTED = 'ADD_ITEM_REJECTED';

export const SAVE_ITEM = 'SAVE_ITEM';
export const SAVE_ITEM_PENDING = 'SAVE_ITEM_PENDING';
export const SAVE_ITEM_FULFILLED = 'SAVE_ITEM_FULFILLED';
export const SAVE_ITEM_REJECTED = 'SAVE_ITEM_REJECTED';
